//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgnacioQuinteros.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empresa
    {
        public int Id { get; set; }
        // TODO: REGEX
        [EmailAddress]
        public string Correo { get; set; }
        [StringLength(100)]
        public string Descripcion { get; set; }
        public Nullable<double> Popularidad { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de creación")]
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
